Portfolio setup and mobile version skeleton
Mehdi-Rh/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2021-11-28 14:39 UTC by Mehdi-Rh

In this PR I am setting the welcome page of my portfolio (mobile version), inspired from Figma Microverse template

Files added:
* readme
*  index.html
* style.css
* stylelintrc.json
Folder added: 
* Images: it contains the background, icons needed for the page.

2021-11-29 09:52 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑❌**
Hello @Mehdi-Rh 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-29 09:52 UTC, emmanuellekamwa commented on README.md
> +This project is MIT licensed.
- [ ] Your readme file is not really presentable. Please try and arrange it so that it can look attractive.

2021-11-29 09:52 UTC, emmanuellekamwa commented on index.html
> +	</section>
- [ ] The container of this section is a header tag. Please try and fix that.

- [ ] Please don't forget to add node modules to the gitignore file

2021-11-29 09:52 UTC, emmanuellekamwa commented on index.html
> +			<div class="logo left">My Logo</div>
- [ ] The logo is on the left and has a link (a tag). Please try and fix that.

2021-11-29 09:52 UTC, emmanuellekamwa commented on index.html
> +			</div>
- [ ] The hamburger button is on the right and has a `nav` tag. Please try and fix that.

2021-11-29 09:52 UTC, emmanuellekamwa commented on index.html
> +		</div>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). Please try and fix that.

2021-11-29 21:34 UTC, rotimiazeez requested changes
# Hi @Mehdi-Rh 👋, 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.😢😢

## Invalid Code Review Request

You have submitted a project, that did not pass all linter checks 🤦‍♂️🤦‍♂️

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2021-11-30 14:09 UTC, Mehdi-Rh commented on index.html
> +			</div>
I make it into a nav tag element and it's ok !!

2021-11-30 15:28 UTC, ShoiraTa approved these changes
## Status: Approved :heavy_check_mark:

Hi @Mehdi-Rh ,  

Your project is complete!. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

## Optional suggestions

 **_Please check comments to see optional suggestions_**

 Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 15:28 UTC, ShoiraTa commented on index.html
> +				<img src="images/Forms/Enabled.png" alt="enabled">
- [ ] [OPTIONAL]: Please consider adding `<humburger>` icon into a `<button>` tag

2021-11-30 15:28 UTC, ShoiraTa commented on index.html
> +				<ul>
- [ ] [OPTIONAL]: Right now all the links are not horizontally aligned, this probably dos not look appealing: 

![image](https://user-images.githubusercontent.com/77038610/144075498-09b2efcb-16cc-45ef-a5a5-d0ea83bc5eb3.png)

✔️  You can easily fix it by using display flex properties:
```
ul {
    display: flex;
    align-items: center;
}
```

2021-11-30 15:53 UTC, Mehdi-Rh commented
Optional comment done !!!

2021-11-30 15:57 UTC, merged