Portfolio setup and mobile version skeleton
Mehdi-Rh/Portfolio-setup-and-mobile-version-skeleton pull request #3
Opened 2021-12-03 22:26 UTC by Mehdi-Rh

In this pull request I will add :

The work section: section containing my projects.
About my self section: It contains my contacts and my social media and my professional skills.

2021-12-03 23:24 UTC, alonsofl requested changes
Hi @Mehdi-Rh,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- Linters working correctly :heavy_check_mark:
- Good use of `grid` and `flexbox` :heavy_check_mark:
- GitHub flow :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 23:24 UTC, alonsofl commented on style.css
> +  left: 0;
- [ ] You have done a good job with the new sections but I would suggest adding the hover effects to your button since it is a project requirement and it will make your portfolio look even better :wink:
![image](https://user-images.githubusercontent.com/81522435/144684077-8d1ffe6d-d5e8-4e67-80f2-21758e898da4.png)

2021-12-03 23:24 UTC, alonsofl commented on index.html
> +				</ul>
- [ ] I think it could be a good idea to update the colors for this text in order to match the Figma design :smiley: :raised_hands:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/144685036-0b874001-b0a5-4c59-b405-dacbeadb3ac5.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/144685062-6f4ce18d-3fbd-4bce-ac50-f52a1c68e445.png)

2021-12-03 23:24 UTC, alonsofl commented on index.html
> +						</ul>
- [ ] I would suggest adding the arrow for this section to match the template. You could check [Material Design](https://materialdesignicons.com/) and download the icons as SVG. **Hint: Look for ``chevron`` to find the arrows** :wink:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/144685320-0edbde3a-72b1-48d3-923d-669fe84eb2e2.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/144685334-71663544-b196-49b8-b41d-97af48760f2a.png)

2021-12-04 14:21 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @Mehdi-Rh ,  

Your project is complete!  Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-04 15:33 UTC, merged

2021-12-07 07:33 UTC, BereketRetta reviewed
- [ ] Good work 😃 but here is one thing left need to be done. At least once like how I selected a few lines and give some suggestions to you 🍀