Contact form mobile version
Mehdi-Rh/Portfolio-setup-and-mobile-version-skeleton pull request #5
Opened 2021-12-07 18:06 UTC by Mehdi-Rh

In this PR, I will  add a **Contact Form** page, it is composed of a text, and a **Form** that includes the following fields:

* User name.
* Email.
* Message field.
* A button to submit the data.

The data will be collected using the Formspree service.

2021-12-07 19:26 UTC, lily-coder requested changes
Hi @Mehdi-Rh , 

Good job so far!🎉🎉🎉

To Highlight! 🟢
✔️ Good job with the linter checks
✔️ Correct Github flow was used

There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://user-images.githubusercontent.com/63964646/145093464-a617190e-c209-42fa-9c42-0e5f4c10e840.png)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Capitalizing your commit messages. This makes your [work professional](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md). You can refer to this link to see [how you can make your commit messages more awesome](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 19:26 UTC, lily-coder commented on style.css
> +.contact-wrapper {
- [ ] [REQUIRED] There is a gap to the right of your portfolio that is uneven with the left. Please fix this so as to match with the original design. 

### YOUR DESIGN
![Cap](https://user-images.githubusercontent.com/63964646/145091390-9104bed9-70d9-4306-96e1-bdee184c2e2b.PNG)

### ORIGINAL DESIGN
![Cap3](https://user-images.githubusercontent.com/63964646/145092026-c5f5e71a-c66d-46f6-b5da-8fcc9b8dd120.PNG)

2021-12-08 10:22 UTC, HENRYKC24 requested changes
# STATUS: CHANGES REQUESTED :recycle: 
## Hi @Mehdi-Rh :wave:, 
![Close](https://media.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif)
Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-08 10:22 UTC, HENRYKC24 commented on style.css
> +.contact-wrapper {
- [ ] Please, try to make sure you address the issues pointed out by the previous reviewer before submitting another pull request. This makes it possible for subsequent reviewers to approve your project easily. 
## Your mobile version as it currently is:point_down:
![image](https://user-images.githubusercontent.com/45668340/145188811-b773bb10-3d4b-45e7-bb3a-e57c6ca4ad6e.png)
If you find it hard to check your mobile version during development, you can [read this article.](https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome)

2021-12-08 10:22 UTC, HENRYKC24 commented on Desktop_version/style.css
> +  max-width: 1440px;
[OPTIONAL] - [ ] Giving your body `min-width`, `max-width` or `width` in this case might be deceptive I think. Test your app with the help of your browser dev tools to make sure you have the actual UI shown to you during development. Combine this with **[CSS media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)**.  [Read this also, please.](https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome)

2021-12-08 10:22 UTC, HENRYKC24 commented on Desktop_version/style.css
> +  width: 1440px;
- [ ] [OPTIONAL] You may consider using relative values for the width of an element. I think you can use percentage values instead of absolute values like `px`. Using absolute values most times causes UI issues.

2021-12-08 11:02 UTC, Mehdi-Rh commented on style.css
> +.contact-wrapper {
Any suggestion, please !!!!!!

2021-12-08 11:50 UTC, Mehdi-Rh commented on style.css
> +.contact-wrapper {
This change should be requested in the first part of the project

2021-12-08 12:28 UTC, HENRYKC24 commented on style.css
> +.contact-wrapper {
You are actually right, but the same change requested is still part of the general requirements of things we are asked to check in your project.

Meanwhile, I tried to check your code to see if I can find out what caused the issue. One of those is giving the body a specific width.

I hope to see you fix this before night today but if you did not, feel free to contact me on slack let's discuss it extensively. Thanks.

2021-12-08 16:10 UTC, HENRYKC24 approved these changes
# STATUS: APPROVED :heavy_check_mark: 
![PERFECT!](https://media.giphy.com/media/YRhUem7n2UaF9EK2PH/giphy.gif)
## Hi @Mehdi-Rh:wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-09 07:01 UTC, merged